version: '3.9'

services:
  postgress: 
    container_name: wave-prisma-postgres
    image:  postgres:16-alpine
    restart: always

    ports: 
     - '5434:5432'
     
    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}    
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - wave-prisma

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
networks:
  wave-prisma: