import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { GoogleAnalytics } from '@next/third-parties/google';
import '../globals.css';

import { routing } from '@/i18n/routing';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import LayoutClientSide from './LayoutClientSide';
import LayoutClientSideFooter from './LayoutClientSideFooter';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Providers } from '@/lib/queryClient';

export const metadata: Metadata = {
  title: 'Wave Engeeneging',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={`bg-[#0B1012]`}>
        <NextIntlClientProvider>
          <main className='flex flex-col  justify-between overflow-hidden '>
            <LayoutClientSide />
            <div className='flex-1'>
              <Providers>{children}</Providers>
            </div>
            <SpeedInsights />
            <LayoutClientSideFooter />
            <GoogleAnalytics gaId='G-0B93WP5255' />
          </main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
